### PR TITLE
Make database timezone agnostic

### LINKED ISSUE #352: BR: business/search endpoint does not correctly make use of timezones.
Steps to reproduce:
- Using swagger create a new business using the `/business/add` endpoint.
- Inspect the created business in the database using `psql` -> `SELECT * FROM businesses;`, for this instance the following is the result:
```
devbusinessregistry=# SELECT * FROM businesses;
 biz_gs1_company_prefix |   biz_name    |          last_update          
------------------------+---------------+-------------------------------
 testmodified           | testmodified  | 2019-01-09 15:38:17.791989+11
(1 rows)
```
- Use swagger to search for the business based on modified time: `/business/search` in this instance `modifiedsince`.
The following results for the above:
```
2019-01-09 14:38+11   - Yes
2019-01-09 15:38+11   - Yes
2019-01-09 16:38+11   - Yes
2019-01-10 02:38+11   - Yes
2019-01-10 03:38+11   - No
```

Where `Yes` is:
```
[
  {
    "businessGS1CompanyPrefix": "testmodified",
    "businessName": "testmodified"
  }
]
```
and `No` is:
```
[]
```

Can also use the following to demonstrate:
```
2019-01-09 15:38Z -- Yes
2019-01-09 16:38Z -- No
```

### PR DESCRIPTION
**Pull request by sajidanower23**
Closes #352 
PG converts `LocalTime` to `UTCTime` based on the system's timezone, and we also convert any time to `UTCTime`, so there is a double conversion. Switching to `TIMESTAMP WITHOUT TIME ZONE` to get around this.

### CODE REVIEW

File: src/Mirza/Common/Beam.hs [hunk 1]
```diff
@@ -44,7 +44,7 @@ textType = BMigrate.DataType pgTextType
 
 -- | Field definition to use for last updated columns
 lastUpdateField :: BMigrate.TableFieldSchema PgColumnSchemaSyntax (Maybe LocalTime)
-lastUpdateField = field "last_update" (maybeType timestamptz) (defaultTo_ (B.just_ now_))
+lastUpdateField = field "last_update" (maybeType timestamp) (defaultTo_ (B.just_ now_))
```
Comment (paulsamways) [inline src/Mirza/Common/Beam.hs]: You need to convert `now()` to UTC

`now() AT TIME ZONE 'UTC'`

Comment (sajidanower23) [reply src/Mirza/Common/Beam.hs]: The triggers are added in the function `Mirza.Common.Utils.addLastUpdateTriggers`, and I have made the `NOW() AT TIME ZONE 'UTC'` change there
